apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
  labels:
    app: todo
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: todo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo-webapp
          image: tsdevopsacp/todo-webapp:latest
          ports:
            - containerPort: 80
